apiVersion: v1
kind: Secret
metadata:
  name: ping-pong-secret
  namespace: ping-pong
type: Opaque
stringData:
  secret.txt: "REPLACE_ME" # In production, use AWS Secrets Manager + External Secrets Operator
