apiVersion: v1
kind: Secret
metadata:
  name: ping-pong-secret
  namespace: default
type: Opaque
stringData:
  secret.txt: "secret" # In real production we will use AWS Secret Manager + External Secret plugin
